version: '3'

services:
  postgres:
    image: 'postgres:16'
    container_name: 'postgres_container'
    ports:
      - "5433:5432"
    volumes:
      - 'E:\pet-projects\postgres-container-data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: denis
      POSTGRES_DB: BigData